name: Build and Deploy
on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
  
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Select build variant
        default: "staging"
        options:
          - staging
          - production
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print variant
        run: |
          echo "Building ${{ inputs.variant }}"